FROM node:22-alpine@sha256:6e80991f69cc7722c561e5d14d5e72ab47c0d6b6cfb3ae50fb9cf9a7b30fdf97
ARG SITE
ENV SITE=${SITE}
ENV PORT=4000
ENV NX_DAEMON=false
WORKDIR /workspace
CMD chown -R $(id -u):$(id -g) ./* && npx nx serve ${SITE} --port ${PORT} --verbose
