FROM node:22-alpine@sha256:51eff88af6dff26f59316b6e356188ffa2c422bd3c3b76f2556a2e7e89d080bd
ARG SITE
ENV SITE=${SITE}
ENV PORT=4000
ENV NX_DAEMON=false
WORKDIR /workspace
CMD chown -R $(id -u):$(id -g) ./* && npx nx serve ${SITE} --port ${PORT} --verbose
