FROM node:22-alpine@sha256:51eff88af6dff26f59316b6e356188ffa2c422bd3c3b76f2556a2e7e89d080bd
ARG SERVICE
WORKDIR /workspace/apps/${SERVICE}
CMD ["npx", "ts-node-dev","-r", "tsconfig-paths/register","src/index.ts" ]
