FROM rabbitmq:management-alpine@sha256:1ccd472932f1464cde1760207dde175cbf7789bd63861efb9da04d40821b19d6

RUN apk add --no-cache curl && rm -rf /var/cache/apk/*

RUN curl -sfL -o /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange.ez https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez

RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange
